version: '3'
services: 
  web:
     image: nginx:1.15-alpine
     ports:
        - "8080:80"
     volumes:
        - ./code:/code
        - ./site.conf:/etc/nginx/conf.d/default.conf
     links:
        - php
  php:
     build:
        context: ./php
        dockerfile: Dockerfile
     image: php:7.1-fpm-graphvic-alpine
     volumes:
        - ./code:/code
